use super::SchemaInvariant;

pub(in crate::migrate) const V086_SCHEMA_INVARIANTS: &[SchemaInvariant] = &[
    SchemaInvariant::table(
        86,
        "memory_activation_boundary",
        "memory_activation_requests",
    ),
    SchemaInvariant::column(
        86,
        "memory_activation_boundary",
        "memory_activation_requests",
        "payload_sha256",
    ),
    SchemaInvariant::column(
        86,
        "memory_activation_boundary",
        "memory_activation_requests",
        "result_sha256",
    ),
    SchemaInvariant::column(
        86,
        "memory_activation_boundary",
        "memory_activation_requests",
        "source_project",
    ),
    SchemaInvariant::index(
        86,
        "memory_activation_boundary",
        "idx_memory_activation_result",
    ),
    SchemaInvariant::trigger(
        86,
        "memory_activation_boundary",
        "memory_activation_requests_no_update",
    ),
    SchemaInvariant::trigger(
        86,
        "memory_activation_boundary",
        "memory_activation_requests_no_delete",
    ),
];
