use super::SchemaInvariant;

pub(in crate::migrate) const V090_SCHEMA_INVARIANTS: &[SchemaInvariant] = &[
    SchemaInvariant::column(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log",
        "activation_id",
    ),
    SchemaInvariant::column(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log",
        "scope_cleanup_response_json",
    ),
    SchemaInvariant::index(
        90,
        "scope_cleanup_receipt",
        "idx_memory_operation_log_activation",
    ),
    SchemaInvariant::table(90, "scope_cleanup_receipt", "memory_scope_cleanup_receipts"),
    SchemaInvariant::index(
        90,
        "scope_cleanup_receipt",
        "idx_memory_scope_cleanup_receipts_operation",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_scope_cleanup_receipts_validate_insert",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_scope_cleanup_receipts_no_update",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_scope_cleanup_receipts_no_delete",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log_activation_no_update",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log_activation_no_replace",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log_activation_validate_update",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_operation_log_activation_no_delete",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_edges_activation_bound_no_insert",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_edges_activation_bound_no_update",
    ),
    SchemaInvariant::trigger(
        90,
        "scope_cleanup_receipt",
        "memory_edges_activation_bound_no_delete",
    ),
];
